global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#alerts'
    send_resolved: true
    title: '{{ template "slack.custom.title" . }}'
    text: '{{ template "slack.custom.text" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'