[project]
name = "prima-api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "boto3"
]

[project.urls]
Homepage = "https://example.com "

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

