apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prima-api-role-binding
  namespace: prima-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prima-api-role
subjects:
- kind: ServiceAccount
  name: prima-api-service-account
  namespace: prima-api