# helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prima-api
  labels:
    app: prima-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prima-api
  template:
    metadata:
      labels:
        app: prima-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: prima-api-config
            - secretRef:
                name: prima-api-secrets