apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
stringData:
  API_KEY: "{{ .Values.env.API_KEY }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.env.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.env.AWS_SECRET_ACCESS_KEY }}"