# API version and resource kind for Kubernetes Secret
apiVersion: v1
kind: Secret

# Metadata section with the name of the secret
metadata:
  # Name of the secret resource
  name: aws-creds

# Secret type; Opaque means arbitrary user-defined data
type: Opaque

# String data fields for the secret; stored as plain text but encoded by Kubernetes
stringData:
  # API key stored as secret data, value pulled from Helm values.yaml
  API_KEY: "{{ .Values.env.API_KEY }}"

  # AWS access key ID stored securely, from Helm values.yaml
  AWS_ACCESS_KEY_ID: "{{ .Values.env.AWS_ACCESS_KEY_ID }}"

  # AWS secret access key stored securely, from Helm values.yaml
  AWS_SECRET_ACCESS_KEY: "{{ .Values.env.AWS_SECRET_ACCESS_KEY }}"
