apiVersion: v1
kind: Secret
metadata:
  name: prima-api-secrets
type: Opaque
stringData:
  API_KEY: "{{ .Values.secrets.API_KEY }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.secrets.AWS_SECRET_ACCESS_KEY }}"