apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  # AWS region for connecting to AWS services
  AWS_REGION: "{{ .Values.env.AWS_REGION }}"

  # Name of the S3 bucket used by the application
  S3_BUCKET: "{{ .Values.env.S3_BUCKET }}"

  # Name of the DynamoDB table used by the application
  DYNAMODB_TABLE: "{{ .Values.env.DYNAMODB_TABLE }}"

