replicaCount: 2
image:
  repository: prima-api
  tag: latest
  pullPolicy: IfNotPresent

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET: ""  # Will be injected via ConfigMap
  DYNAMODB_TABLE: ""  # Will be injected via ConfigMap

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80