apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: prima-api
spec:
  selector:
    app: xray-daemon
  ports:
  - name: xray-udp
    port: 2000
    protocol: UDP
    targetPort: 2000