replicaCount: 1

image:
  repository: prima-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "prima-tech-user-avatars"
  DYNAMODB_TABLE_NAME: "users"
  
