apiVersion: apps/v1
kind: Deployment
metadata:
  name: prima-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prima-app
  template:
    metadata:
      labels:
        app: prima-app
    spec:
      containers:
      - name: prima-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: prima-app-config
        - secretRef:
            name: aws-creds
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10