replicaCount: 1

image:
  repository: abz7896/prima-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE_NAME: "users"
  AWS_ACCESS_KEY_ID: "local-access-key"
  AWS_SECRET_ACCESS_KEY: "local-secret-key"
  API_KEY: "local-api-key"
  S3_BUCKET: "local-bucket"
  DYNAMODB_TABLE: "local-table"

