name: CI/CD Pipeline

on:
  push:
    branches:
      - release
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply & Output
    runs-on: ubuntu-latest
    outputs:
      s3_bucket: ${{ steps.terraform-outputs.outputs.s3_bucket }}
      dynamodb_table: ${{ steps.terraform-outputs.outputs.dynamodb_table }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: terraform-outputs
        working-directory: ./infra
        run: |
          echo "s3_bucket=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
          echo "dynamodb_table=$(terraform output -raw dynamodb_table_name)" >> $GITHUB_OUTPUT

  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t mydockeruser/prima-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push mydockeruser/prima-app:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes with Helm
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Helm Upgrade / Install
        run: |
          helm upgrade --install prima-app ./charts/prima-app \
            --namespace prima-challenge --create-namespace \
            --set env.S3_BUCKET=${{ needs.terraform.outputs.s3_bucket }} \
            --set env.DYNAMODB_TABLE=${{ needs.terraform.outputs.dynamodb_table }} \
            --set image.repository=mydockeruser/prima-app \
            --set image.tag=${{ github.sha }}
