name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Static Analysis
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create venv and install linters
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          pip install --upgrade pip
          pip install flake8 mypy bandit safety black isort

      - name: Black
        run: black --check app/ tests/
        continue-on-error: true

      - name: Isort
        run: isort --check-only app/ tests/
        continue-on-error: true

      - name: Flake8
        run: flake8 app/ tests/
        continue-on-error: true

      - name: Bandit
        run: bandit -r app/ --severity-level high
        continue-on-error: true

      - name: Mypy
        run: mypy app/
        continue-on-error: true

      - name: Safety Check
        run: |
          pip install -r requirements.txt
          safety check --key=${{ secrets.SAFETY_API_KEY }}
        continue-on-error: true

  iac-scan:
    name: IaC Scanning
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Checkov
        run: pip install checkov
        continue-on-error: true

      - name: Run Checkov
        run: checkov -d . --output --output-file-path iac_checkov_report
        continue-on-error: true

      - name: Upload Checkov Report
        uses: actions/upload-artifact@v4
        with:
          name: iac-checkov
          path: iac_checkov_report.*
        continue-on-error: true

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          version: latest

      - name: Run TFLint
        run: tflint --recursive
        continue-on-error: true

  test-suite:
    name: Test Suite
    runs-on: self-hosted
    needs: lint
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: pip

      - name: Create venv and install test deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
          pip install pytest pytest-cov moto locust

      - name: Unit Tests
        run: pytest tests/unit -v --cov=app --cov-report=xml

      - name: Integration Tests
        run: pytest tests/integration -v --cov=app --cov-append
        continue-on-error: true

      - name: Security Tests
        run: pytest tests/security -v
        continue-on-error: true

      - name: Validation Tests
        run: pytest tests/validation -v
        continue-on-error: true

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

  performance:
    name: Performance Tests
    runs-on: self-hosted
    needs: test-suite
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create venv and install Locust
        run: |
          python -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          pip install locust

      - name: Load Test
        run: |
          locust -f tests/performance/test_load.py --headless \
            -u 100 -r 10 -t 30s \
            --csv=load_test_results \
            --html=load_test_report.html
        continue-on-error: true

      - name: Upload Load Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: load-test-results
          path: |
            load_test_results*
            load_test_report.html

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: [test-suite, performance]
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            abz7896/prima-api:${{ github.sha }}
            abz7896/prima-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/prima-api \
            prima-api=abz7896/prima-api:${{ github.sha }}
          kubectl rollout status deployment/prima-api --timeout=90s

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel: '#alerts'
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
