# .github/workflows/deploy.yaml
name: Prima API CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set build tag
        run: |
          # Use timestamp like 20250405-1234
          echo "BUILD_TAG=20250405-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abz7896/prima-api:${{ env.BUILD_TAG }}
          build-args: |
            BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%SZ'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy with Helm
        run: |
          helm upgrade --install prima-api helm/ \
            --set image.repository=abz7896/prima-api \
            --set image.tag=${{ env.BUILD_TAG }} \
            --set secret.AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --set secret.AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --set secret.API_KEY=${{ secrets.API_KEY }} \
            --set config.AWS_REGION=${{ secrets.AWS_REGION }} \
            --set config.S3_BUCKET=${{ secrets.S3_BUCKET }} \
            --set config.DYNAMODB_TABLE=${{ secrets.DYNAMODB_TABLE }}