name: Prima API CI/CD

on:
  push:
    branches:
      - feature/python-api-server-final

jobs:
  build:
    name: Build Docker Image & Lint Python
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      API_KEY: ${{ secrets.API_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
    outputs:
      build_tag: ${{ steps.set_tag.outputs.build_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies + bandit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt bandit

      - name: Run Security Scan (bandit)
        run: bandit -r app

      - name: Set build tag for Docker image
        id: set_tag
        run: |
          BUILD_TAG=dev-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          echo "::set-output name=build_tag::${BUILD_TAG}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abz7896/prima-api:${{ env.BUILD_TAG }}

  terraform:
    name: Terraform Format, Init & Apply
    runs-on: ubuntu-latest
    needs: build
    environment: release
    permissions:
      contents: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      API_KEY: ${{ secrets.API_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
    steps:     
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Terraform CLI v1.8.5
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: Terraform format check
        run: terraform fmt -check
        working-directory: terraform

      - name: Terraform init
        run: terraform init
        working-directory: terraform

      - name: Terraform validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform apply (auto-approve)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
        
      - name: Output Terraform state info
        run: |
          terraform output -json > ../terraform.json
          cat ../terraform.json
        working-directory: terraform

  tests:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    needs: terraform
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest (unit + integration)
        run: pytest --maxfail=3 --disable-warnings -q

  helm_lint:
    name: Helm Chart Linting
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      API_KEY: ${{ secrets.API_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Helm CLI v3.11.3
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Helm lint
        run: helm lint ./helm

  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [tests, helm_lint]
    environment: dev
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push to dev branch
        run: |
          git fetch origin
          git checkout dev || git checkout -b dev
          git pull origin feature/python-api-server-final --allow-unrelated-histories || echo "No remote feature branch to pull"
          git merge origin/feature/python-api-server-final --no-edit --allow-unrelated-histories || echo "Merge completed"
          git push origin dev

  deploy-release:
    name: Deploy to Release
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: ${{ needs.deploy-dev.result == 'success' }}
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push to release branch
        run: |
          git fetch origin
          git checkout release || git checkout -b release
          git pull origin dev --allow-unrelated-histories || echo "No remote dev branch to pull"
          git merge origin/dev --no-edit --allow-unrelated-histories || echo "Merge completed"
          git push origin release

  deploy-main:
    name: Deploy to Main
    runs-on: ubuntu-latest
    needs: deploy-release
    if: ${{ needs.deploy-release.result == 'success' }}
    environment: main
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Push to main branch
        run: |
          git fetch origin
          git checkout main || git checkout -b main
          git pull origin release --allow-unrelated-histories || echo "No remote release branch to pull"
          git merge origin/release --no-edit --allow-unrelated-histories || echo "Merge completed"
          git push origin main

  notify-slack-dev:
    name: Slack Notification - Dev
    runs-on: ubuntu-latest
    if: always()
    needs: deploy-dev
    steps:
      - name: Send Slack Status for Dev
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚀 Dev Deployment\nWorkflow: ${{ github.workflow }}\nStatus: ${{ needs.deploy-dev.result }}\nBranch: ${{ github.ref_name }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-slack-release:
    name: Slack Notification - Release
    runs-on: ubuntu-latest
    if: always()
    needs: deploy-release
    steps:
      - name: Send Slack Status for Release
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚀 Release Deployment\nWorkflow: ${{ github.workflow }}\nStatus: ${{ needs.deploy-release.result }}\nBranch: ${{ github.ref_name }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-slack-main:
    name: Slack Notification - Main
    runs-on: ubuntu-latest
    if: always()
    needs: deploy-main
    steps:
      - name: Send Slack Status for Main
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "🚀 Main Deployment\nWorkflow: ${{ github.workflow }}\nStatus: ${{ needs.deploy-main.result }}\nBranch: ${{ github.ref_name }}\nBy: ${{ github.actor }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}